### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by richard-ramos** [status-im/waku-react-native#2]

**Comment by richard-ramos** [comment]
Done! The package was [published](https://www.npmjs.com/package/@waku/react-native) successfully!
During the publishing the following issues were found:
1. It was necessary to execute `yarn login` before publishing, otherwise, publishing would not work (it would complain about an invalid 2FA pin even if it was correct)
2. Gowaku IOS library would include symbolic links which are not allowed in npm. Before publishing, this [script](https://github.com/status-im/waku-react-native/blob/master/ios/clean-sym-links.sh) should be run to remove these.
3. To publish the following instruction must be executed: `yarn publish --access public --network-timeout 9999999`. This is a heavy package, and not specifying the timeout would end up causing the publish process to fail

cc: @D4nte

**Comment by D4nte** [comment]
1. Could you open an issue on yarn repo? :)
2. :+1: 
3. You can add the `--access public` in the package.json file: 

```
  "publishConfig" : {
    "access": "public"
  },
```
